"""adds special_requests column

Revision ID: 13ac8fd8f556
Revises: 162bc37d204b
Create Date: 2025-10-31 00:28:51.136264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ac8fd8f556'
down_revision = '162bc37d204b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_requests', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('special_requests')

    # ### end Alembic commands ###
