"""New migration

Revision ID: 563a42218dc9
Revises: d1e3d1f2e173
Create Date: 2025-10-29 10:59:52.625364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563a42218dc9'
down_revision = 'd1e3d1f2e173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('property_images',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('property_id', sa.Integer(), nullable=False),
    # sa.Column('image_url', sa.String(length=500), nullable=False),
    # sa.Column('thumbnail_url', sa.String(length=500), nullable=False),
    # sa.Column('public_id', sa.String(length=200), nullable=False),
    # sa.Column('is_primary', sa.Boolean(), nullable=True),
    # sa.Column('display_order', sa.Integer(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('payments', schema=None) as batch_op:
    #     batch_op.alter_column('payment_date',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_properties_student_id', 'users', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_properties_student_id', type_='foreignkey')
        batch_op.drop_column('student_id')
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('type')

    # with op.batch_alter_table('payments', schema=None) as batch_op:
    #     batch_op.alter_column('payment_date',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)

    # op.drop_table('property_images')
    # ### end Alembic commands ###
